<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    //==========================================================================================================================================
    /*
    问：什么情况下会报错【Uncaught (in promise) 】?
    答：当 Promise 实例状态切换成 rejected 后，但没有指定的失败的回调
        这时候就会报这个错误
    */
    //==========================================================================================================================================
    
    //==========================================================================================================================================
    /*
    问：但为什么 Promise 实例状态切换成 fulfilled 后，但没有指定的成功的回调
        反而没有报错
    答：按照常理，是要报错的，但是Promise做了处理
        发现 实例 状态切换为成功后，觉得是个值得高兴的事情，就算没有 成功的回调也不要紧
        就不给予抛出错误了
    */
    //==========================================================================================================================================
    
    //==========================================================================================================================================
    /*
    注意🎈：【Uncaught (in promise) 】的这中报错不会影响js的运行
            该错误会在js所以程序都执行完后，在最后被抛出
    */
    //==========================================================================================================================================
    
    
    
    
  </script>
</body>
</html>