<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    //==========================================================================================================================================
    /*
    问：then方法返回的返回值，也是一个全新的 promise 实例，
        那么该实例的状态该怎么去改变它？
    答：该实例的状态的改变分以下几种情况
        1：当 promise实例.then 方法管理的异步回调（不管是成功还是失败的异步回调）的返回值为【非 promise实例 类型】时
        【新的Promise实例 = promise实例.then()】新的Promise实例 的状态都会切换成成功，
        且成功的 value 就是前面异步回调返回的【 非 promise实例 类型值】
        2：当 promise实例.then 方法管理的异步回调（不管是成功还是失败的异步回调）的返回值为【 promise实例 类型】时
        【新的Promise实例 = promise实例.then()】新的Promise实例 的状态改变分以下 3 种情况
          2.1：返回值为【 promise实例 pending 的状态】时，新的Promise实例 的状态也会是 pending【pending状态是没有值得, 且也不会调用then方法里任何一个回调】
          2.2：返回值为【 promise实例 fulfilled 的状态】时，新的Promise实例 的状态也会是 fulfilled，
          value 就是返回值切换成为 fulfilled 时 传入的 value 
          2.3：返回值为【 promise实例 rejected 的状态】时，新的Promise实例 的状态也会是 rejected
          reason 就是返回值切换成为失败 rejected 时 传入的 reason 
        3：当 promise实例.then 方法管理的异步回调（不管是成功还是失败的异步回调）出现异常时
        promise实例.then 返回的 Promise 实例状态将是 rejected ，且 reason 就是抛出的异常
    */
    /* // 1：
    const p  = new Promise((resolve, reject) => {
      reject("error's reason--1")
    })

    const pp = p.then(
      value => {
        console.log(value,  'p-->', p)
      },
      reason => {
        console.log(reason,  'p-->', p) //2
        return "ssuccess's value-2"
      }
    )
    pp.then(
      value => {
        console.log(value, 'pp-->', pp) //3
      },
      reason => {
        console.log(reason,  'pp-->', pp)
      }
    )
    console.log(`主线程：pp-->${pp}`) //1 */
    
    /* // 2.1：
    const p  = new Promise((resolve, reject) => {
      reject("error's reason--1")
    })

    const pp = p.then(
      value => {
        console.log(value,  'p-->', p)
      },
      reason => {
        console.log(reason,  'p-->', p) //2
        return new Promise((resolve, reject) => {})
      }
    )
    pp.then(
      value => {
        console.log(value, 'pp-->', pp) //3
      },
      reason => {
        console.log(reason,  'pp-->', pp)
      }
    )
    console.log(`主线程：pp-->`, pp) //1  */

    /* // 2.2：
    const p  = new Promise((resolve, reject) => {
      reject("error's reason--1")
    })

    const pp = p.then(
      value => {
        console.log(value,  'p-->', p)
      },
      reason => {
        console.log(reason,  'p-->', p) //2
        return Promise.resolve("success's value--2")
      }
    )
    pp.then(
      value => {
        console.log(value, 'pp-->', pp) //3
      },
      reason => {
        console.log(reason,  'pp-->', pp)
      }
    )
    console.log(`主线程：pp-->`, pp) //1  */
    
    /* // 2.3：
    const p  = new Promise((resolve, reject) => {
      reject("error's reason--1")
    })

    const pp = p.then(
      value => {
        console.log(value,  'p-->', p)
      },
      reason => {
        console.log(reason,  'p-->', p) //2
        return Promise.reject("error's reason--2")
      }
    )
    pp.then(
      value => {
        console.log(value, 'pp-->', pp) //3
      },
      reason => {
        console.log(reason,  'pp-->', pp)
      }
    )
    console.log(`主线程：pp-->`, pp) //1  */
    
    /* // 3：
    const p = new Promise((resolve, reject) => {
      // throw 111
      console.log(a);
    })
    p.then(
      value => {
        console.log('value:', value, 'p', p)
      },
      reason => {
        console.log('reason:', reason, 'p', p)
      }
    ) */
    //==========================================================================================================================================
    
    
    
  </script>
</body>
</html>