<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    //==========================================================================================================================================
    /*
    问：为什么要终端 Promise实例.then() 的连续调用？
    答：因为一组连续有先后的异步请求在用then方法连续调用时
        就算其中某个请求失败，这组请求还是会连续往后调用then里的回调
    问：怎么去终端呢？
    答：在每个then管理的失败的回调函数内，返回一个状态为 pending 的 promise 实例
    */

    function sendAjaxGet(url, data){
      return new Promise((resolve, reject) => {

        const xhr = new XMLHttpRequest()

        xhr.onreadystatechange = () => {
          if (xhr.readyState === 4) {
            console.log(444444)
            if (xhr.status >= 200 && xhr.status < 300) 
              resolve(xhr.response)
            else reject('失败了')
          }
        }

        let str = ''

        for (const key in data) {
          if (Object.hasOwnProperty.call(data, key)) {
            str += `${key}=${data[key]}&`
          }
        }

        str = str.slice(0, -1)

        xhr.open("GET", url+'?'+str)

        xhr.responseType = 'json'

        xhr.send()

      })
    }
  
    /* // 为什么要终端 Promise实例.then() 的连续调用？
    sendAjaxGet(
      'http://127.0.0.1:8081:test_jquery_get',
      {a:'aa'}
    )
    .then(
      value => {
        console.log('1:第一次请求成功', value)
        return sendAjaxGet('http://127.0.0.1:8081/test_jquery_get',{a:'aa'})
      },
      reason => {
        console.log('1:第一次请求失败', reason)
      }
    )
    .then(
      value => {
        console.log('2:第2次请求成功', value)
        return sendAjaxGet('http://127.0.0.1:8081/test_jquery_get',{a:'aa'})
      },
      reason => {
        console.log('2:第2次请求失败', reason)
      }
    )
    .then(
      value => {
        console.log('3:第3次请求成功', value)
        return sendAjaxGet('http://127.0.0.1:8081/test_jquery_get',{a:'aa'})
      },
      reason => {
        console.log('3:第3次请求失败', reason)
      }
    ) */
    
    // 问：怎么去终端呢？
    sendAjaxGet(
      'http://127.0.0.1:8081:test_jquery_get',
      {a:'aa'}
    )
    .then(
      value => {
        console.log('1:第一次请求成功', value)
        return sendAjaxGet('http://127.0.0.1:8081/test_jquery_get',{a:'aa'})
      },
      reason => {
        console.log('1:第一次请求失败', reason)
        return new Promise((resolve, reject) => {})
      }
    )
    .then(
      value => {
        console.log('2:第2次请求成功', value)
        return sendAjaxGet('http://127.0.0.1:8081/test_jquery_get',{a:'aa'})
      },
      reason => {
        console.log('2:第2次请求失败', reason)
        return new Promise((resolve, reject) => {})

      }
    )
    .then(
      value => {
        console.log('3:第3次请求成功', value)
        return sendAjaxGet('http://127.0.0.1:8081/test_jquery_get',{a:'aa'})
      },
      reason => {
        console.log('3:第3次请求失败', reason)
        return new Promise((resolve, reject) => {})
      }
    )
    //==========================================================================================================================================
    
    
    
  </script>
</body>
</html>